import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {motion,AnimatePresence} from 'framer-motion';
import {ArrowUpRight, Code2, BriefcaseBusiness, Mail, Sparkles, X} from 'lucide-react';
import {answerFromResume} from './resumeData';
import './styles.css';

const projects=[
 {name:'Imlea',tag:'learning platform',desc:'A learning platform for kids to study their school curriculum.',tech:'Education · Learning · Kids'},
 {name:'Resume Roaster',tag:'AI product',desc:'An AI tool that turns a resume into practical, brutally useful feedback.',tech:'LLMs · Product · Web'},
 {name:'LinkGenie',tag:'agent',desc:'An agentic resume-link workflow built around turning a profile into a shareable experience.',tech:'Agents · Automation'},
 {name:'Cart Healthifier',tag:'GenAI',desc:'An LLM-powered experiment focused on understanding cart health and useful product signals.',tech:'LLMs · Data · Product'},
 {name:'Anomalyzer',tag:'GTM + AI',desc:'Product and GTM work around making anomaly intelligence easier to understand and adopt.',tech:'AI · GTM · Content'}
];
const career=[
 {year:'Jul 2025 to Aug 2026',name:'Grid Dynamics',role:'AI Engineer · Generative AI',detail:'Built production GenAI agents, RAG pipelines, developer tools, and AI scenario workflows.',impact:'VISA agent used by 200 to 300 users · 40 engineering hours saved weekly · 80% RAG retrieval accuracy'},
 {year:'Feb 2025 to Jun 2025',name:'Paysecure',role:'Software Engineer',detail:'Built payment integrations, a merchant support chatbot, and Redis based backend utilities.',impact:'Payment plugin used by 40 merchants · integrations across 3 commerce platforms · support response time improved by 60%'},
 {year:'Dec 2022 to Nov 2024',name:'Zomato',role:'Software Engineer',detail:'Worked across HyperPure orders, OCR, GenAI evaluation, regional languages, and automation.',impact:'Parchi Orders covered about 70% of company GMV · invoice extraction cost reduced by over 80% · 35 hours saved weekly'}
];
const openSource=[
 {name:'Care4ther',desc:'An open source project helping users get advance awareness of accidents.',tech:'Public repository · 68 stars',url:'https://github.com/unnati914/Care4ther-'},
 {name:'Hirvana Website',desc:'A TypeScript web project with a documented GitHub code push workflow.',tech:'Public repository · TypeScript',url:'https://github.com/unnati914/hirvana-website'},
 {name:'OopsBot',desc:'A Streamlit excuse-maker that generates believable or absurd excuses for missed texts.',tech:'Public repository · Python · Streamlit',url:'https://github.com/unnati914/OopsBot'}
];
const failures=[
 {name:'X dating',idea:'Build for dating on X.',outcome:'It stayed an experiment instead of becoming a shipped product.',lesson:'Interesting questions are still useful, even when the product does not continue.'},
 {name:'built it in 24 hours',idea:'Move fast and test the idea immediately.',outcome:'The prototype worked, then the next problem was scaling it.',lesson:'A fast first version is only the beginning of the real problem.'},
 {name:'technically worked',idea:'Solve the problem well enough to ship.',outcome:'It worked, but nobody cared enough to use it.',lesson:'A working product still needs a reason for people to return.'},
 {name:'questionable idea',idea:'Follow the strange idea and see what happens.',outcome:'It was still shipped, even if it was not the right idea.',lesson:'Shipping creates better evidence than protecting an idea forever.'}
];
const excuseLines=[
 'The project is almost done. One tiny detail remains.',
 'The feature works perfectly, as long as nobody clicks anything unexpected.',
 'It is not delayed. It is collecting highly valuable feedback from reality.',
 'The project is 90% done. The remaining 10% has formed a committee.'
];
const vibeChecks=[
 'Vibe check: deployable. Confidence: suspiciously high.',
 'Diagnostics complete. One more tab has been opened for research.',
 'All systems nominal. The CSS has requested a meeting.',
 'Build passed. Product scope has quietly doubled.'
];
const personalityModes=[
 {id:'recruiter',label:'recruiter'},
 {id:'collaborator',label:'collaborator'},
 {id:'curious',label:'curious human'},
 {id:'technical',label:'technical deep dive'}
];
function App(){
 const [ask,setAsk]=useState(false); const [q,setQ]=useState(''); const [answer,setAnswer]=useState(''); const [selectedCareer,setSelectedCareer]=useState(0); const [personality,setPersonality]=useState('curious'); const [guestNote,setGuestNote]=useState(''); const [recruiterView,setRecruiterView]=useState(false); const [accessibilityMode,setAccessibilityMode]=useState(false); const [alternateReality,setAlternateReality]=useState(false); const [quizChoice,setQuizChoice]=useState(''); const [quizAnswered,setQuizAnswered]=useState(false); const [fortune,setFortune]=useState(''); const [excuse,setExcuse]=useState(''); const [excuseIndex,setExcuseIndex]=useState(0); const [vibeCheck,setVibeCheck]=useState(''); const [vibeIndex,setVibeIndex]=useState(0);
 const addGuestNote=e=>{e.preventDefault(); const text=guestNote.trim(); if(!text)return; setGuestNote(''); window.location.href=`mailto:chhabraunnati234@gmail.com?subject=${encodeURIComponent('Guestbook note from your website')}&body=${encodeURIComponent(text)}`;};
 const respond=(input=q)=>{const question=input.trim(); if(!question)return; const framing={recruiter:'Quick context: ',collaborator:'If you are thinking about working with Unnati: ',curious:'The short version: ',technical:'Technical lens: '}; const reply=answerFromResume(question); setAnswer(reply.startsWith('I can answer questions')?'I don’t know that from the information I have. I would rather say that than make something up.':framing[personality]+reply);};
 const showFortune=()=>setFortune(failures[Math.floor(Math.random()*failures.length)].lesson);
 const generateExcuse=()=>{setExcuse(excuseLines[excuseIndex%excuseLines.length]);setExcuseIndex(excuseIndex+1);};
 const runVibeCheck=()=>{setVibeCheck(vibeChecks[vibeIndex%vibeChecks.length]);setVibeIndex(vibeIndex+1);};
 const isNotFound=window.location.pathname!=='/'&&window.location.pathname!=='/index.html';
 if(isNotFound)return <main className="not-found"><span className="section-label">404 · experiment escaped</span><h1>This page has entered its unexplained experiment era.</h1><p>No route found. The good news: this one is definitely not a product decision.</p><a className="primary" href="/">back to the actual website <ArrowUpRight size={18}/></a></main>;
 return <div className={`${recruiterView?'app recruiter-view':'app'}${accessibilityMode?' accessibility-mode':''}`}>
  <header><a className="logo" href="#top">UC<span>.</span></a><nav><a href="#work">work</a><a href="#career">career</a><a href="#lab">lab</a><button onClick={()=>setAsk(true)}>ask unnati ↗</button><button className="recruiter-toggle" onClick={()=>setRecruiterView(!recruiterView)}>{recruiterView?'full site':'recruiter view'}</button><button className="setting-toggle" aria-pressed={accessibilityMode} onClick={()=>setAccessibilityMode(!accessibilityMode)}>{accessibilityMode?'normal text':'accessibility'}</button></nav></header>
  <main id="top">
  <section className="hero"><div className="eyebrow"><span className="dot"/> currently building with AI</div><h1>I build <em>AI systems</em>,<br/>agents & products<br/>that actually ship.</h1><p className="lede">I’m Unnati Chhabra, an AI Engineer / Data Scientist working across GenAI, agentic systems, backend engineering and weird ideas worth building.</p><div className="actions"><a className="primary" href="#work">explore my work <ArrowUpRight size={18}/></a><a className="secondary" href="mailto:chhabraunnati234@gmail.com">say hi <Mail size={16}/></a><a className="secondary" href="/resume.pdf" download>resume <ArrowUpRight size={16}/></a></div><div className="scroll">↓ scroll to explore</div></section>
    <section className="now"><div className="section-label">01 / now</div><div className="now-grid"><div><h2>what’s cooking</h2><p>Not a static portfolio. This is a snapshot of what I’m actually thinking, building and shipping.</p></div><div className="status-card"><div><span className="pill live">● building</span><h3>Imlea</h3><p>A learning platform for kids to study their school curriculum.</p><div className="mini-quiz"><strong>tiny study break</strong><p>Which one is a primary color?</p><div>{['Blue','Green','Pink'].map(choice=><button className={quizChoice===choice?'chosen':''} key={choice} onClick={()=>{setQuizChoice(choice);setQuizAnswered(true)}}>{choice}</button>)}</div>{quizAnswered&&<p className="quiz-result">Gold star for playing, {quizChoice==='Blue'?'and you got it right':'even when the answer was Blue'}: ★</p>}</div></div><span className="arrow">↗</span></div><div className="status-card"><div><span className="pill">● experimenting</span><h3>AI product lab</h3><p>Small MVPs, agent workflows and ideas tested by shipping.</p></div><span className="arrow">↗</span></div></div></section>
   <section className="counter"><div className="big-number">27</div><div><div className="section-label">things shipped / experiments started</div><p>Some became products. Some became lessons. A few became very expensive tabs.</p></div></section>
   <section id="work" className="work"><div className="section-label">02 / selected work</div><h2>things I’ve built<br/><span>& worked on</span></h2><div className="projects">{projects.map((p,i)=><motion.article key={p.name} className="project" initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.04}}><div className="project-top"><span>0{i+1}</span><span className="tag">{p.tag}</span></div><h3>{p.name}<ArrowUpRight size={20}/></h3><p>{p.desc}</p><small>{p.tech}</small></motion.article>)}</div></section>
  <section id="career" className="career"><div className="section-label">03 / career graph</div><h2>different problems.<br/><span>same obsession.</span></h2><div className="timeline">{career.map((c,i)=><motion.div className={selectedCareer===i?'career-row selected':'career-row'} key={c.name} role="button" tabIndex="0" initial={{opacity:0,x:-24}} whileInView={{opacity:1,x:0}} viewport={{once:true,margin:'-60px'}} transition={{duration:.5,delay:i*.14}} onClick={()=>setSelectedCareer(i)} onKeyDown={e=>(e.key==='Enter'||e.key===' ')&&setSelectedCareer(i)}><div className="year">{c.year}</div><div className="node">{i===0?'✦':'·'}</div><div className="career-copy"><h3>{c.name}</h3><strong>{c.role}</strong><p>{alternateReality&&c.name==='Zomato'?'Alternate timeline: Unnati stayed at Zomato and became the unofficial Parchi whisperer. The orders still flow; the nickname is still under review.':c.detail}</p><div className="career-impact"><span>impact</span>{c.impact}</div></div></motion.div>)}</div><button className="fun-button" onClick={()=>setAlternateReality(!alternateReality)}>{alternateReality?'back to real timeline':'what if alternate timeline?'} ↗</button><div className="recruiter-disclaimer recruiter-only">Optimized for scanning. May contain traces of personality.</div></section>
  <section className="skills recruiter-only"><div className="section-label">skills</div><h2>tools for turning<br/><span>ideas into systems.</span></h2><div className="skill-list">{['Python','Java','JavaScript','SQL','LLMs','RAG','Prompt Engineering','pgvector','Agentic Systems','REST APIs','Redis','PostgreSQL','Node.js','React','Next.js','Streamlit','Docker','Kubernetes','CI/CD'].map(skill=><span key={skill}>{skill}</span>)}</div></section>
  <section className="education"><div className="section-label">04 / education</div><div className="education-grid"><div><h2>where it<br/><span>started.</span></h2><p>The foundation behind the systems, products, and experiments.</p></div><div className="education-card"><span className="year">Aug 2019 to May 2023</span><h3>Indira Gandhi Delhi Technical University for Women</h3><strong>B.Tech · Information Technology</strong><p>Delhi, India · CGPA 8.01</p></div></div></section>
  <section className="open-source"><div className="section-label">05 / open source</div><div className="open-source-grid"><div><h2>share the<br/><span>work.</span></h2><p>Public projects, community work, and contributions collected from GitHub.</p><div className="opensource-note"><strong>Community</strong><span>GitHub Campus Expert · Former LFX Mentee · Founder of CodXCrypt</span><a href="https://github.com/unnati914" target="_blank" rel="noreferrer">view GitHub profile ↗</a></div></div><div className="projects open-source-projects">{openSource.map((project,index)=><a className="project open-source-project" href={project.url} target="_blank" rel="noreferrer" key={project.name}><div className="project-top"><span>0{index+1}</span><span className="tag">github</span></div><h3>{project.name}<ArrowUpRight size={20}/></h3><p>{project.desc}</p><small>{project.tech}</small></a>)}</div></div></section>
  <section id="lab" className="lab"><div className="section-label">06 / failure archive</div><div className="lab-grid"><div><h2>failed experiments<br/><span>are still work.</span></h2><p>I keep the messy stuff too. Every failed experiment gets a short record: the idea, what happened, and what changed afterward.</p><button className="fun-button" onClick={showFortune}>open a failure fortune cookie ↗</button>{fortune&&<blockquote className="fortune-cookie">{fortune}</blockquote>}<div className="oops-generator"><div className="section-label">oopsbot says</div><h3>the project is almost done...</h3><button className="fun-button" onClick={generateExcuse}>make it more dramatic ↗</button>{excuse&&<p className="generated-excuse">“{excuse}”</p>}</div></div>{failures.map((failure,index)=><article className="failure" key={failure.name}><span>0{index+1}</span><h3>{failure.name}</h3><div className="failure-story"><strong>idea</strong><p>{failure.idea}</p><strong>what happened</strong><p>{failure.outcome}</p><strong>learned</strong><p>{failure.lesson}</p></div></article>)}</div></section>
  <section className="terminal-card"><div className="terminal-head"><span>unnati@portfolio ~</span><span>● ● ●</span></div><div className="terminal-body"><p>$ whoami</p><p className="muted">AI engineer · builder · community person</p><p>$ ls current_work/</p><p>imlea/ &nbsp; ai-agents/ &nbsp; evals/ &nbsp; experiments/</p><p>$ echo “what matters?”</p><p className="accent">ship → learn → iterate → repeat</p><button className="vibe-button" onClick={runVibeCheck}>run vibe check ↗</button>{vibeCheck&&<p className="vibe-result">$ {vibeCheck}</p>}</div></section>
    <section className="contact"><div className="section-label">07 / contact</div><h2>building something<br/><em>interesting?</em></h2><p>Send a hello. Tell me what you're building. Or just say hi as a person.</p><div className="contact-links"><a href="mailto:chhabraunnati234@gmail.com">email <Mail size={16}/></a><a href="https://github.com/unnati914" target="_blank" rel="noreferrer">github <Code2 size={16}/></a><a href="https://www.linkedin.com/in/unnati-chhabra-/" target="_blank" rel="noreferrer">linkedin <BriefcaseBusiness size={16}/></a><a href="https://www.instagram.com/unnatiisig/" target="_blank" rel="noreferrer">instagram <span className="instagram-icon" aria-hidden="true"><i/></span></a></div><div className="guestbook"><div><div className="section-label">leave a note</div><h3>what should I build next?</h3></div><form onSubmit={addGuestNote}><input value={guestNote} maxLength="180" onChange={e=>setGuestNote(e.target.value)} placeholder="a thought, idea, or hello..."/><button type="submit">email this note ↗</button></form></div></section>
  </main>
  <footer><span>© 2026 unnati chhabra</span><span>built with curiosity + too many tabs</span><div className="footer-links"><a href="https://www.linkedin.com/in/unnati-chhabra-/" target="_blank" rel="noreferrer">linkedin</a><a href="https://github.com/unnati914" target="_blank" rel="noreferrer">github</a><a href="mailto:chhabraunnati234@gmail.com">email</a><a href="https://www.instagram.com/unnatiisig/" target="_blank" rel="noreferrer">instagram <span className="instagram-icon" aria-hidden="true"><i/></span></a></div></footer>
  <AnimatePresence>{ask&&<motion.div className="overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setAsk(false)}><motion.div className="ask-modal" initial={{y:30,scale:.98}} animate={{y:0,scale:1}} exit={{y:30,scale:.98}} onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setAsk(false)}><X/></button><div className="section-label">ask unnati · resume brain</div><h2>what do you want<br/>to know?</h2><div className="personality-modes"><span>answer as</span>{personalityModes.map(mode=><button className={personality===mode.id?'active':''} key={mode.id} onClick={()=>setPersonality(mode.id)}>{mode.label}</button>)}</div><div className="ask-input"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&respond()} placeholder="e.g. what does she build?"/><button onClick={respond}>↗</button></div>{answer&&<div className="answer"><Sparkles size={16}/>{answer}</div>}<div className="suggestions">{['what does she build?','tell me about Imlea','what’s her stack?'].map(x=><button key={x} onClick={()=>{setQ(x);respond(x)}}>{x}</button>)}</div></motion.div></motion.div>}</AnimatePresence>
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
